let mixerData=[
    {
        "id":1,
        "image":"https://rukminim2.flixcart.com/image/312/312/ko0d6kw0/mixer-grinder-juicer/0/h/u/plus-butterfly-original-imag2kadbfjzzayj.jpeg?q=70",
        "price":3999,
        "name":"Butterfly"
    },
    {
        "id":2,
        "image":"https://rukminim2.flixcart.com/image/312/312/ko0d6kw0/mixer-grinder-juicer/0/h/u/plus-butterfly-original-imag2kadbfjzzayj.jpeg?q=70",
        "price":2999,
        "name":"Bajaj"
    },
    {
        "id":3,
        "image":"https://rukminim2.flixcart.com/image/312/312/jylvde80/mixer-grinder-juicer/z/j/d/bosch-mgm8642bin-original-imafgsy4rdhvzmvg.jpeg?q=70",
        "price":5999,
        "name":"Bosch"
    },
    {
        "id":4,
        "image":"https://rukminim2.flixcart.com/image/312/312/jylvde80/mixer-grinder-juicer/z/j/d/bosch-mgm8642bin-original-imafgsy4rdhvzmvg.jpeg?q=70",
        "price":6339,
        "name":"sujatha"
    },
    {
        "id":5,
        "image":"https://rukminim2.flixcart.com/image/312/312/jylvde80/mixer-grinder-juicer/z/j/d/bosch-mgm8642bin-original-imafgsy4rdhvzmvg.jpeg?q=70",
        "price":2499,
        "name":"OWO"
    },
    {
        "id":6,
        "image":"https://rukminim2.flixcart.com/image/312/312/jylvde80/mixer-grinder-juicer/z/j/d/bosch-mgm8642bin-original-imafgsy4rdhvzmvg.jpeg?q=70",
        "price":1398,
        "name":"dice"
    },
]