let tvData=[
    {
        "id":1,
        "image":"https://rukminim2.flixcart.com/image/312/312/xif0q/television/2/9/w/-original-imagxx9u2eh9rbqn.jpeg?q=70",
        "price":14490,
        "name":"LG"
    },
    {
        "id":2,
        "image":"https://rukminim2.flixcart.com/image/312/312/xif0q/television/1/z/i/-original-imagyk8ttgzxvs2s.jpeg?q=70",
        "price":30999,
        "name":"Samsung"
    },
    {
        "id":3,
        "image":"https://rukminim2.flixcart.com/image/312/312/xif0q/television/c/y/h/-original-imagsjjgjsmz2rvz.jpeg?q=70",
        "price":16999,
        "name":"Acer"
    },
    {
        "id":4,
        "image":"https://rukminim2.flixcart.com/image/312/312/xif0q/television/y/w/a/-original-imagxymf3brdz7gh.jpeg?q=70",
        "price":14999,
        "name":"Redmi"
    },
    {
        "id":5,
        "image":"https://rukminim2.flixcart.com/image/312/312/xif0q/television/g/u/x/-original-imagtr9smhkgcamw.jpeg?q=70",
        "price":16999,
        "name":"iffalcon"
    },
    {
        "id":6,
        "image":"https://rukminim2.flixcart.com/image/312/312/xif0q/television/z/m/z/-original-imagtzxtaqfzregz.jpeg?q=70",
        "price":16999,
        "name":"Motorola"
    },
    {
        "id":7,
        "image":"https://rukminim2.flixcart.com/image/312/312/xif0q/television/y/0/0/-original-imagvgcge6n7ewzc.jpeg?q=70",
        "price":35999,
        "name":"Sony"
    },
    {
        "id":8,
        "image":"https://rukminim2.flixcart.com/image/312/312/krme93k0/television/8/j/w/kd-55x80j-kd-55x80j-sony-original-imag5dfgzut79ate.jpeg?q=70",
        "price":58999,  
        "name":"Sony"
    },
    {
        "id":9,
        "image":"https://rukminim2.flixcart.com/image/312/312/xif0q/television/e/f/y/-original-imagtvefvp4xhkt6.jpeg?q=70",
        "price":45678,
        "name":"LG"
    },
]