let washingData=[
    {
        "id":1,
        "image":"https://rukminim2.flixcart.com/image/312/312/xif0q/washing-machine-new/k/c/l/-original-imagx7qhzg4f3bca.jpeg?q=70",
        "price":15999,
        "name":"lG Semi-automatic"
    },
    {
        "id":2,
        "image":"https://rukminim2.flixcart.com/image/312/312/xif0q/washing-machine-new/k/c/l/-original-imagx7qhzg4f3bca.jpeg?q=70",
        "price":13999,
        "name":"Whirlpool"
    },
    {
        "id":3,
        "image":"https://rukminim2.flixcart.com/image/312/312/xif0q/washing-machine-new/k/c/l/-original-imagx7qhzg4f3bca.jpeg?q=70",
        "price":15999,
        "name":"RealMe techlife"
    },
    {
        "id":4,
        "image":"https://rukminim2.flixcart.com/image/312/312/xif0q/washing-machine-new/k/c/l/-original-imagx7qhzg4f3bca.jpeg?q=70",
        "price":22999,
        "name":"LG"
    },
    {
        "id":5,
        "image":"https://rukminim2.flixcart.com/image/312/312/xif0q/washing-machine-new/k/c/l/-original-imagx7qhzg4f3bca.jpeg?q=70",
        "price":17999,
        "name":"Samsung"
    },
    {
        "id":6,
        "image":"https://rukminim2.flixcart.com/image/312/312/xif0q/washing-machine-new/u/y/x/-original-imagvc2zvu97vgqs.jpeg?q=70",
        "price":23999,
        "name":"Samsung"
    },
    {
        "id":7,
        "image":"https://rukminim2.flixcart.com/image/312/312/xif0q/washing-machine-new/u/y/x/-original-imagvc2zvu97vgqs.jpeg?q=70",
        "price":19999,
        "name":"IFB"
    },
    {
        "id":8,
        "image":"https://rukminim2.flixcart.com/image/312/312/xif0q/washing-machine-new/u/y/x/-original-imagvc2zvu97vgqs.jpeg?q=70",
        "price":25999,
        "name":"Motorolla"
    },
    {
        "id":9,
        "image":"https://rukminim2.flixcart.com/image/312/312/xif0q/washing-machine-new/q/z/3/-original-imags8stbjkgy8he.jpeg?q=70",
        "price":12899,
        "name":"Godrej"
    },
]